Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 15

AllCops:
  Include:
    - lib/**/*
  Exclude:
    - spec/**/*
    - done/**/*
    - examples/**/*
